### ISSUE TITLE
Not Working with IoS

### ISSUE THREAD

**Issue by Gohith** [JoaoLopesF/Esp-Mobile-Apps-Esp32#3]
Hi,
Had implemented the esp_app code successfully, but there is an issue, which it is only discoverable on android but not on ios and while building the app in Xcode, I would like to know what should we need to mention @ "peripheral start name" in "centralManager Function"  >>  BLE.swift file ???

Thank You,
Gohith

**Comment by BewareARP** [comment]
what is the last conclusion?
